-- Gerado a partir de scripts/exercise-image-matches.json
-- Cole este conteúdo no SQL Editor do Supabase e clique em RUN.
-- Atualiza só a coluna images, por slug — não mexe em mais nada.

UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press/1.jpg'] WHERE slug = 'supino-reto-barra'; -- Barbell Bench Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/1.jpg'] WHERE slug = 'supino-reto-halteres'; -- Dumbbell Bench Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Barbell_Bench_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Barbell_Bench_Press/1.jpg'] WHERE slug = 'supino-inclinado-barra'; -- Incline Barbell Bench Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/1.jpg'] WHERE slug = 'supino-inclinado-halteres'; -- Incline Dumbbell Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Flyes/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Flyes/1.jpg'] WHERE slug = 'crucifixo-halteres'; -- Dumbbell Flyes
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/1.jpg'] WHERE slug = 'crossover-polia'; -- Cable Crossover
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/1.jpg'] WHERE slug = 'flexao-braco'; -- Pushups
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dips_-_Triceps_Version/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dips_-_Triceps_Version/1.jpg'] WHERE slug = 'paralelas-mergulho'; -- Dips - Triceps Version
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Lat_Pulldown/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Lat_Pulldown/1.jpg'] WHERE slug = 'puxada-frontal'; -- Front Lat Pulldown
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/1.jpg'] WHERE slug = 'barra-fixa'; -- Pullups
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/1.jpg'] WHERE slug = 'remada-curvada-barra'; -- Bent Over Barbell Row
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/1.jpg'] WHERE slug = 'remada-baixa-polia'; -- Seated Cable Rows
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/1.jpg'] WHERE slug = 'remada-halter-serrote'; -- One-Arm Dumbbell Row
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/1.jpg'] WHERE slug = 'levantamento-terra'; -- Barbell Deadlift
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Pullover/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Pullover/1.jpg'] WHERE slug = 'pullover-halter'; -- Dumbbell Pullover
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/1.jpg'] WHERE slug = 'face-pull'; -- Face Pull
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/1.jpg'] WHERE slug = 'agachamento-livre-barra'; -- Barbell Squat
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/1.jpg'] WHERE slug = 'leg-press-45'; -- Leg Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/1.jpg'] WHERE slug = 'cadeira-extensora'; -- Leg Extensions
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/1.jpg'] WHERE slug = 'mesa-flexora'; -- Lying Leg Curls
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/1.jpg'] WHERE slug = 'cadeira-flexora-sentada'; -- Seated Leg Curl
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stiff-Legged_Barbell_Deadlift/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stiff-Legged_Barbell_Deadlift/1.jpg'] WHERE slug = 'stiff-barra'; -- Stiff-Legged Barbell Deadlift
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/1.jpg'] WHERE slug = 'rdl-romanian-deadlift'; -- Romanian Deadlift
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/1.jpg'] WHERE slug = 'afundo-lunge'; -- Dumbbell Lunges
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/1.jpg'] WHERE slug = 'panturrilha-pe'; -- Standing Calf Raises
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/1.jpg'] WHERE slug = 'panturrilha-sentada'; -- Seated Calf Raise
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Split_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Split_Squat/1.jpg'] WHERE slug = 'agachamento-bulgaro'; -- Dumbbell Split Squat
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/1.jpg'] WHERE slug = 'hack-machine'; -- Hack Squat
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Squat/1.jpg'] WHERE slug = 'agachamento-smith'; -- Smith Machine Squat
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thigh_Abductor/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thigh_Abductor/1.jpg'] WHERE slug = 'cadeira-abdutora'; -- Thigh Abductor
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Adductor/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Adductor/1.jpg'] WHERE slug = 'cadeira-adutora'; -- Adductor
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/1.jpg'] WHERE slug = 'elevacao-pelvica-hip-thrust'; -- Barbell Hip Thrust
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Glute_Kickback/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Glute_Kickback/1.jpg'] WHERE slug = 'gluteo-cabo-coice'; -- Cable Glute Kickback
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Military_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Military_Press/1.jpg'] WHERE slug = 'desenvolvimento-militar-barra'; -- Standing Military Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/1.jpg'] WHERE slug = 'desenvolvimento-halteres'; -- Dumbbell Shoulder Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/1.jpg'] WHERE slug = 'elevacao-lateral-halteres'; -- Side Lateral Raise
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Dumbbell_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Dumbbell_Raise/1.jpg'] WHERE slug = 'elevacao-frontal-halteres'; -- Front Dumbbell Raise
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Machine_Flyes/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Machine_Flyes/1.jpg'] WHERE slug = 'crucifixo-inverso-peck-reverse'; -- Reverse Machine Flyes
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shrug/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shrug/1.jpg'] WHERE slug = 'encolhimento-halteres'; -- Dumbbell Shrug
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/1.jpg'] WHERE slug = 'triceps-pulley'; -- Triceps Pushdown
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Rope_Triceps_Pushdown/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Rope_Triceps_Pushdown/1.jpg'] WHERE slug = 'triceps-corda'; -- Cable Rope Triceps Pushdown
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Skullcrusher/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Skullcrusher/1.jpg'] WHERE slug = 'triceps-frances'; -- EZ-Bar Skullcrusher
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/1.jpg'] WHERE slug = 'triceps-banco'; -- Bench Dips
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/1.jpg'] WHERE slug = 'mergulho-bancos'; -- Bench Dips
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/1.jpg'] WHERE slug = 'rosca-direta-barra'; -- Barbell Curl
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bicep_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bicep_Curl/1.jpg'] WHERE slug = 'rosca-direta-halteres'; -- Dumbbell Bicep Curl
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Alternate_Dumbbell_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Alternate_Dumbbell_Curl/1.jpg'] WHERE slug = 'rosca-alternada'; -- Standing Alternate Dumbbell Curl
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Hammer_Curls/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Hammer_Curls/1.jpg'] WHERE slug = 'rosca-martelo'; -- Dumbbell Hammer Curls
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/1.jpg'] WHERE slug = 'rosca-scott'; -- Preacher Curl
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Concentration_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Concentration_Curl/1.jpg'] WHERE slug = 'rosca-concentrada'; -- Dumbbell Concentration Curl
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/1.jpg'] WHERE slug = 'prancha-plank'; -- Plank
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunches/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunches/1.jpg'] WHERE slug = 'abdominal-supra'; -- Crunches
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Flat_Bench_Lying_Leg_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Flat_Bench_Lying_Leg_Raise/1.jpg'] WHERE slug = 'infra-banca'; -- Flat Bench Lying Leg Raise
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Plank/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Plank/1.jpg'] WHERE slug = 'prancha-lateral'; -- Side Plank
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bicycle_Crunches/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bicycle_Crunches/1.jpg'] WHERE slug = 'abdominal-bicicleta'; -- Bicycle Crunches
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/1.jpg'] WHERE slug = 'hanging-leg-raise'; -- Hanging Leg Raise
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shrug/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shrug/1.jpg'] WHERE slug = 'encolhimento-barra'; -- Barbell Shrug
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Barbell_Row/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Barbell_Row/1.jpg'] WHERE slug = 'remada-alta-barra'; -- Upright Barbell Row
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wrist_Curls/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wrist_Curls/1.jpg'] WHERE slug = 'punho-barra'; -- Wrist Curls
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Wrist_Curls/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Wrist_Curls/1.jpg'] WHERE slug = 'punho-invertido'; -- Reverse Wrist Curls
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/1.jpg'] WHERE slug = 'hip-thrust-barra'; -- Barbell Hip Thrust
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/1.jpg'] WHERE slug = 'agachamento-goblet'; -- Goblet Squat
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stiff-Legged_Dumbbell_Deadlift/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stiff-Legged_Dumbbell_Deadlift/1.jpg'] WHERE slug = 'stiff-halteres'; -- Stiff-Legged Dumbbell Deadlift
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Step_Ups/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Step_Ups/1.jpg'] WHERE slug = 'avanco-step-up'; -- Dumbbell Step Ups
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Sumo_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Sumo_Squat/1.jpg'] WHERE slug = 'sumo-squat-halter'; -- Dumbbell Sumo Squat
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Good_Morning/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Good_Morning/1.jpg'] WHERE slug = 'good-morning'; -- Good Morning
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Hip_Adduction/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Hip_Adduction/1.jpg'] WHERE slug = 'cadeira-adutora-cabo'; -- Cable Hip Adduction
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Swings/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Swings/1.jpg'] WHERE slug = 'kettlebell-swing'; -- Kettlebell Swings
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Barbell_Bench_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Barbell_Bench_Press/1.jpg'] WHERE slug = 'supino-declinado-barra'; -- Decline Barbell Bench Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Flyes/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Flyes/1.jpg'] WHERE slug = 'crucifixo-inclinado-halteres'; -- Incline Dumbbell Flyes
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Lateral_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Lateral_Raise/1.jpg'] WHERE slug = 'elevacao-lateral-polia'; -- Cable Lateral Raise
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/1.jpg'] WHERE slug = 'desenvolvimento-arnold'; -- Arnold Dumbbell Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/1.jpg'] WHERE slug = 'remada-unilateral-halter'; -- One-Arm Dumbbell Row
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight-Arm_Pulldown/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight-Arm_Pulldown/1.jpg'] WHERE slug = 'pulldown-pulley'; -- Straight-Arm Pulldown
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift/1.jpg'] WHERE slug = 'levantamento-terra-sumo'; -- Sumo Deadlift
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Barbell_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Barbell_Squat/1.jpg'] WHERE slug = 'agachamento-frontal'; -- Front Barbell Squat
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Extension/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Extension/1.jpg'] WHERE slug = 'cadeira-extensora-unilateral'; -- Single Leg Extension
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/1.jpg'] WHERE slug = 'leg-press-90'; -- Leg Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Calf_Press_On_The_Leg_Press_Machine/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Calf_Press_On_The_Leg_Press_Machine/1.jpg'] WHERE slug = 'panturrilha-leg-press'; -- Calf Press On The Leg Press Machine
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Glute_Bridge/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Glute_Bridge/1.jpg'] WHERE slug = 'elevacao-pelvica-unilateral'; -- Single Leg Glute Bridge
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Kickbacks/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Kickbacks/1.jpg'] WHERE slug = 'coice-gluteo-solo'; -- Glute Kickbacks
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lying_Triceps_Extension/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lying_Triceps_Extension/1.jpg'] WHERE slug = 'triceps-testa-halteres'; -- Dumbbell Lying Triceps Extension
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Kickbacks/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Kickbacks/1.jpg'] WHERE slug = 'triceps-coice'; -- Triceps Kickbacks
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Curl/1.jpg'] WHERE slug = 'rosca-direta-polia'; -- Cable Curl
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Wrist_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Wrist_Curl/1.jpg'] WHERE slug = 'rosca-punho-polia'; -- Cable Wrist Curl
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/1.jpg'] WHERE slug = 'abdominal-polia'; -- Cable Crunch
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/1.jpg'] WHERE slug = 'abdominal-infra-barra'; -- Hanging Leg Raise
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/1.jpg'] WHERE slug = 'russian-twist'; -- Russian Twist
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/T-Bar_Row/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/T-Bar_Row/1.jpg'] WHERE slug = 'remada-t-bar'; -- T-Bar Row
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/1.jpg'] WHERE slug = 'terra-romeno-barra'; -- Romanian Deadlift
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/1.jpg'] WHERE slug = 'cadeira-flexora-deitada'; -- Lying Leg Curls
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Good_Morning/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Good_Morning/1.jpg'] WHERE slug = 'good-morning-halteres'; -- Dumbbell Good Morning
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Freehand_Jump_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Freehand_Jump_Squat/1.jpg'] WHERE slug = 'jump-squat'; -- Freehand Jump Squat
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mountain_Climbers/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mountain_Climbers/1.jpg'] WHERE slug = 'mountain-climber'; -- Mountain Climbers
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Diamond_Push-Ups/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Diamond_Push-Ups/1.jpg'] WHERE slug = 'flexao-diamante'; -- Diamond Push-Ups
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Archer_Push-Ups/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Archer_Push-Ups/1.jpg'] WHERE slug = 'flexao-arqueira'; -- Archer Push-Ups
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Dumbbell_Bench_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Dumbbell_Bench_Press/1.jpg'] WHERE slug = 'supino-declinado-halteres'; -- Decline Dumbbell Bench Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/1.jpg'] WHERE slug = 'crossover-baixa'; -- Cable Crossover
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Dumbbell_Flyes/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Dumbbell_Flyes/1.jpg'] WHERE slug = 'crucifixo-declinado-halteres'; -- Decline Dumbbell Flyes
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Push-Up/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Push-Up/1.jpg'] WHERE slug = 'flexao-inclinada'; -- Incline Push-Up
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Push-Up/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Push-Up/1.jpg'] WHERE slug = 'flexao-declinada'; -- Decline Push-Up
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dips_-_Triceps_Version/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dips_-_Triceps_Version/1.jpg'] WHERE slug = 'paralelas'; -- Dips - Triceps Version
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Bench_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Bench_Press/1.jpg'] WHERE slug = 'press-peito-maquina'; -- Machine Bench Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/1.jpg'] WHERE slug = 'supino-halteres-plano'; -- Dumbbell Bench Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Ups/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Ups/1.jpg'] WHERE slug = 'barra-fixa-supinada'; -- Chin-Ups
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Front_Lat_Pulldown/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Front_Lat_Pulldown/1.jpg'] WHERE slug = 'puxada-neutra'; -- Close-Grip Front Lat Pulldown
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/V-Bar_Pulldown/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/V-Bar_Pulldown/1.jpg'] WHERE slug = 'puxada-triangulo'; -- V-Bar Pulldown
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Grip_Bent-Over_Rows/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Grip_Bent-Over_Rows/1.jpg'] WHERE slug = 'remada-curvada-supinada'; -- Reverse Grip Bent-Over Rows
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/T-Bar_Row/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/T-Bar_Row/1.jpg'] WHERE slug = 'remada-tbar'; -- T-Bar Row
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/1.jpg'] WHERE slug = 'remada-serrote'; -- One-Arm Dumbbell Row
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/1.jpg'] WHERE slug = 'remada-baixa-neutra'; -- Seated Cable Rows
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight-Arm_Pulldown/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight-Arm_Pulldown/1.jpg'] WHERE slug = 'pullover-polia-alta'; -- Straight-Arm Pulldown
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/1.jpg'] WHERE slug = 'pull-down-polia'; -- Wide-Grip Lat Pulldown
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/1.jpg'] WHERE slug = 'terra-romeno'; -- Romanian Deadlift
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift/1.jpg'] WHERE slug = 'terra-sumo'; -- Sumo Deadlift
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Good_Morning/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Good_Morning/1.jpg'] WHERE slug = 'good-morning-barra'; -- Good Morning
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/1.jpg'] WHERE slug = 'mesa-flexora-sentada'; -- Seated Leg Curl
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/1.jpg'] WHERE slug = 'cadeira-flexora-unilateral'; -- Lying Leg Curls
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/1.jpg'] WHERE slug = 'agachamento-hack'; -- Hack Squat
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/1.jpg'] WHERE slug = 'avanco-lunge'; -- Dumbbell Lunges
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Lunge/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Lunge/1.jpg'] WHERE slug = 'avanco-lateral'; -- Barbell Lunge
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/1.jpg'] WHERE slug = 'avanco-reverse'; -- Dumbbell Lunges
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/1.jpg'] WHERE slug = 'panturrilha-pe-unilateral'; -- Standing Calf Raises
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/1.jpg'] WHERE slug = 'hip-thrust-halteres'; -- Barbell Hip Thrust
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Glute_Kickback/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Glute_Kickback/1.jpg'] WHERE slug = 'gluteo-coice-polia'; -- Cable Glute Kickback
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Hip_Adduction/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Hip_Adduction/1.jpg'] WHERE slug = 'abducao-quadril-polia'; -- Cable Hip Adduction
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Glute_Bridge/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Glute_Bridge/1.jpg'] WHERE slug = 'elevacao-pelvica'; -- Barbell Glute Bridge
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Kickbacks/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Kickbacks/1.jpg'] WHERE slug = 'coice-maquina'; -- Glute Kickbacks
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Sumo_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Sumo_Squat/1.jpg'] WHERE slug = 'agachamento-sumo-halter'; -- Dumbbell Sumo Squat
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Step_Ups/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Step_Ups/1.jpg'] WHERE slug = 'step-up'; -- Dumbbell Step Ups
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Shoulder_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Shoulder_Press/1.jpg'] WHERE slug = 'desenvolvimento-maquina'; -- Machine Shoulder Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Upright_Row/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Upright_Row/1.jpg'] WHERE slug = 'remada-alta-halteres'; -- Standing Dumbbell Upright Row
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Cable_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Cable_Raise/1.jpg'] WHERE slug = 'elevacao-frontal-polia'; -- Front Cable Raise
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Reverse_Fly/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Reverse_Fly/1.jpg'] WHERE slug = 'crucifixo-inverso-polia'; -- Cable Reverse Fly
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Shrug/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Shrug/1.jpg'] WHERE slug = 'encolhimento-maquina'; -- Machine Shrug
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Triceps_Extension/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Triceps_Extension/1.jpg'] WHERE slug = 'triceps-frances-halter'; -- Standing Dumbbell Triceps Extension
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Triceps_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Triceps_Press/1.jpg'] WHERE slug = 'triceps-frances-sentado'; -- Seated Triceps Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Grip_Triceps_Pushdown/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Grip_Triceps_Pushdown/1.jpg'] WHERE slug = 'triceps-polia-supinada'; -- Reverse Grip Triceps Pushdown
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/1.jpg'] WHERE slug = 'mergulho-banco'; -- Bench Dips
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Triceps_Extension/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Triceps_Extension/1.jpg'] WHERE slug = 'triceps-maquina'; -- Machine Triceps Extension
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Diamond_Push-Ups/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Diamond_Push-Ups/1.jpg'] WHERE slug = 'flexao-maos-juntas'; -- Diamond Push-Ups
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Curl/1.jpg'] WHERE slug = 'rosca-polia'; -- Cable Curl
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternate_Hammer_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternate_Hammer_Curl/1.jpg'] WHERE slug = 'rosca-martelo-polia'; -- Alternate Hammer Curl
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Barbell_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Barbell_Curl/1.jpg'] WHERE slug = 'rosca-inversa'; -- Reverse Barbell Curl
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Wrist_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Wrist_Curl/1.jpg'] WHERE slug = 'flexao-pulso-halter'; -- Dumbbell Wrist Curl
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Wrist_Curls/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Wrist_Curls/1.jpg'] WHERE slug = 'extensao-pulso-halter'; -- Reverse Wrist Curls
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wrist_Curls/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wrist_Curls/1.jpg'] WHERE slug = 'encolhimento-pulso'; -- Wrist Curls
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/1.jpg'] WHERE slug = 'abdominal-infra'; -- Hanging Leg Raise
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/1.jpg'] WHERE slug = 'prancha'; -- Plank
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/1.jpg'] WHERE slug = 'elevacao-pernas-barra'; -- Hanging Leg Raise
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Exercise_Ball_Crunch/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Exercise_Ball_Crunch/1.jpg'] WHERE slug = 'abdominal-bola-suica'; -- Exercise Ball Crunch
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Running_Treadmill/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Running_Treadmill/1.jpg'] WHERE slug = 'corrida-esteira'; -- Running, Treadmill
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bicycling_Stationary/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bicycling_Stationary/1.jpg'] WHERE slug = 'bicicleta-ergometrica'; -- Bicycling, Stationary
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elliptical_Trainer/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elliptical_Trainer/1.jpg'] WHERE slug = 'eliptico'; -- Elliptical Trainer
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rowing_Stationary/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rowing_Stationary/1.jpg'] WHERE slug = 'remo-ergometro'; -- Rowing, Stationary
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Jump/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Jump/1.jpg'] WHERE slug = 'pular-corda'; -- Bench Jump
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Battling_Ropes/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Battling_Ropes/1.jpg'] WHERE slug = 'battle-rope'; -- Battling Ropes
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Box_Jump/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Box_Jump/1.jpg'] WHERE slug = 'box-jump'; -- Front Box Jump
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hug_A_Ball/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hug_A_Ball/1.jpg'] WHERE slug = 'wall-ball'; -- Hug A Ball
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Leg_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Leg_Curl/1.jpg'] WHERE slug = 'cadeira-flexora-pe'; -- Standing Leg Curl
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Pistol_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Pistol_Squat/1.jpg'] WHERE slug = 'agachamento-pistol'; -- Kettlebell Pistol Squat
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Weighted_Sissy_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Weighted_Sissy_Squat/1.jpg'] WHERE slug = 'sissy-squat'; -- Weighted Sissy Squat
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Freehand_Jump_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Freehand_Jump_Squat/1.jpg'] WHERE slug = 'agachamento-pulsao'; -- Freehand Jump Squat
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Thruster/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Thruster/1.jpg'] WHERE slug = 'thruster'; -- Kettlebell Thruster
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clean_and_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clean_and_Press/1.jpg'] WHERE slug = 'clean-and-press'; -- Clean and Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Snatch/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Snatch/1.jpg'] WHERE slug = 'snatch'; -- Snatch
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Barbell_Bench_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Barbell_Bench_Press/1.jpg'] WHERE slug = 'supino-fechado-barra'; -- Close-Grip Barbell Bench Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/1.jpg'] WHERE slug = 'supino-fechado-halteres'; -- Dumbbell Bench Press
UPDATE "Exercise" SET images = ARRAY['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/1.jpg'] WHERE slug = 'woodchopper-polia'; -- Cable Crossover
